services:
  go-cloud:
    build: ./
    command: bash -c './wait-connection.sh db migrate -path ./schema -database postgres://postgres:${DB_PASSWORD}@db:5432/postgres?sslmode=disable up && ./goCLoudTask'
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
